spring:
  datasource:
    url: jdbc:mysql://localhost/listacontato
    username: root
    password: dudsdnave
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    database: mysql
    show-sql: true
    defer-datasource-initialization: true
  jackson:
    time-zone: America/Sao_Paulo
  output:
    ansi:
      enabled: Always

springdoc:
  show-login-endpoint: true

server:
  error:
    include-stacktrace: never
  port: 8085

management:
  server:
    port: 8086
  endpoints:
    web:
      exposure:
        include: "*"